const ACTIONS = 'actions'
const DIAGNOSTIC = 'diagnostic'
const EDIT_CARD = 'edit-card'
const EDIT_STALL = 'edit-stall'

const ADMIN_RIGHTS = [ACTIONS, DIAGNOSTIC, EDIT_CARD, EDIT_STALL]
const SERVICE_RIGHTS = [ACTIONS, EDIT_CARD, EDIT_STALL]
const VALET_RIGHTS = []
const USER_RIGHTS = []

module.exports = {
  ADMIN_RIGHTS: ADMIN_RIGHTS,
  SERVICE_RIGHTS: SERVICE_RIGHTS,
  USER_RIGHTS: USER_RIGHTS,
  VALET_RIGHTS: VALET_RIGHTS
}
